name: Create
run-name: ${{ github.actor }} create
on: [workflow_dispatch]
jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Report Header
        run: |
          echo "The job was triggered by a ${{ github.event_name }} event."
          echo "The operating system this job is now running on is ${{ runner.os }}."
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Clone Repository
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Repository Listing
        run: |
          ls ${{ github.workspace }}
      - name: Install OpenTofu
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method standalone
      - name: Initialize
        working-directory: ./tofu
        run: tofu init
      - name: Plan Deployment
        working-directory: ./tofu
        run: tofu plan
      - name: Upload OpenTofu State
        uses: actions/upload-artifact@v4
        with:
          name: tfstate
          path: |
            ${{ github.workspace }}/tofu/.terraform.tfstate
            ${{ github.workspace }}/tofu/.terraform.tfstate.backup
      - name: Full Path Listing
        working-directory: /
        run: tree
      - name: Status
        run: echo "This job's status is ${{ job.status }}."
